[project]
name = "grantdao"
description = "Community grants distribution platform"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.grantdao]
path = "contracts/grantdao.clar"

[repl.analysis]
passes = ["check_checker"]
